
user_name_textbox = "/html/body/app-root/app-login/div/div/div/div[2]/div/form/div[1]/input"
password_textbox = "/html/body/app-root/app-login/div/div/div/div[2]/div/form/div[2]/input"
login_button = "/html/body/app-root/app-login/div/div/div/div[2]/div/div[1]/button"
pop_up_username = "//*[@id='i0116']"
pop_up_submit_button= "/html/body/div/form[1]/div/div/div[2]/div[1]/div/div/div/div/div[1]/div[3]/div/div/div/div[4]/div/div/div/div/input"
pop_up_pass ="//*[@id='i0118']"
pop_up_submit = "/html/body/div/form[1]/div/div/div[2]/div[1]/div/div/div/div/div/div[3]/div/div[2]/div/div[4]/div[2]/div/div/div/div/input"
pop_up_button= "/html/body/div/form/div/div/div[2]/div[1]/div/div/div/div/div/div[3]/div/div[2]/div/div[3]/div[2]/div/div/div[2]/input"
welcome_page="/html/body/app-home/main/article/div/div/app-internal-dashboard/section/div/h1"
jump_to_client_dropdown="/html/body/app-home/main/article/div/header/div[1]/div[2]/div[1]/div/div/div"
Amazon_dropdown_value= "/html/body/app-home/main/article/div/header/div[1]/div[2]/div[2]/div/div[1]/div[2]/a[1]/span"
Add_plan_button= "/html/body/app-home/main/article/div/div/app-dashboard/div/div/section[1]/button/span"
search_vision_textbox="/html/body/div/div[2]/div/mat-dialog-container/app-plans-list/div/div[1]/div/div[2]/form/div/input"
search_click="/html/body/div/div[2]/div/mat-dialog-container/app-plans-list/div/div[1]/div/div[2]/form/div/input"
vision_plan_link="/html/body/div/div[2]/div/mat-dialog-container/app-plans-list/div/div[2]/div/a/span[2]"
save_and_add_button="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[8]/div[1]/button"
policy_number_textbox="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[1]/input"
plan_name_textbox="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[3]/input"
document_category="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[4]/select"
select_value_document_category="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[4]/select/option[2]"
secondary_document_category="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[5]/select"
select_value_secondary_doc="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[5]/select/option[3]"
generic_document_name="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[6]/select"
select_generic_document="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[6]/select/option[2]"
business_level="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[7]/select"
select_business_level="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[7]/select/option[2]"
carrier="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[9]/select/option[1]"
select_carrier="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[9]/select/option[4]"
plan_id="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[10]/label/input"
plan_start_date="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[11]/div/mat-form-field/div/div[1]/div[2]/mat-datepicker-toggle/button"
select_plan_date="/html/body/div[1]/div[2]/div/mat-datepicker-content/div[2]/mat-calendar/div/mat-month-view/table/tbody/tr[5]/td[6]/div[1]"
plan_status="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[12]/select"
select_plan_status="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[12]/select/option[2]"
issuing_location= "/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[13]/select"
select_issuing_location="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[13]/select/option[4]"
commission_textbox="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[14]/input"
tier="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[15]/select"
select_tier="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[15]/select/option[2]"
search_tag="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[19]/input"
internal_tag="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[20]/input"
display_to_client="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[21]/div/input"
region_selector_textbox="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[22]/input"
class_selector_textbox="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[23]/input"
display_name_textbox="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[24]/input"

summary_dropdown="/html/body/app-home/main/article/div/div/app-dashboard/div/div/section[1]/div/div[1]/h3"
plan_year="/html/body/app-home/main/article/div/div/app-dashboard/div/div/section[1]/section/div[1]/nav/button[2]"
group_by_dropdown="/html/body/app-home/main/article/div/div/app-dashboard/div/div/section[1]/section/div[2]/div/div[1]/div/div"
select_carrier_dropdown="/html/body/app-home/main/article/div/div/app-dashboard/div/div/section[1]/section/div[2]/div/div[2]/a[2]"

view_all_link_text="/html/body/app-home/main/article/div/div/app-dashboard/div/aside/div/div/a"

select_existing_plan="/html/body/div[1]/div[2]/div/mat-dialog-container/app-account-activity-viewall/div[2]/div[1]/div[2]/div[1]/a"
edit_plan_button="/html/body/app-home/main/article/div/div/app-view-plan-details/div/app-plan-summaries/div/section[2]/form/div[1]/section/div/a"
edit_policy_number="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[1]/div/div[1]/input"
update_plan_button="/html/body/app-home/main/article/div/div/app-dynamic-forms/form/div[8]/button"


amazon_dashboard="/html/body/app-home/main/article/div/div/app-dashboard/section/div"

username_label="/html/body/app-root/app-login/div/div/div/div[2]/div/form/div[1]/label"
plan_start_year_click="/html/body/div[1]/div[2]/div/mat-datepicker-content/div[2]/mat-calendar/mat-calendar-header/div/div/button[1]"
select_plan_year="/html/body/div[1]/div[2]/div/mat-datepicker-content/div[2]/mat-calendar/div/mat-multi-year-view/table/tbody/tr[1]/td[1]/div[1]"
select_month="/html/body/div[1]/div[2]/div/mat-datepicker-content/div[2]/mat-calendar/div/mat-year-view/table/tbody/tr[4]/td[1]/div[1]"